INSERT INTO co.t_cocktails VALUES (96, 'Americano', 'https://en.wikipedia.org/wiki/Americano_(cocktail)');
INSERT INTO co.t_cocktails VALUES (97, 'Angel Face', 'https://en.wikipedia.org/wiki/Angel_Face_(cocktail)');
INSERT INTO co.t_cocktails VALUES (98, 'Aviation', 'https://en.wikipedia.org/wiki/Aviation_(cocktail)');
INSERT INTO co.t_cocktails VALUES (99, 'Between the Sheets', 'https://en.wikipedia.org/wiki/Between_the_Sheets_(cocktail)');
INSERT INTO co.t_cocktails VALUES (100, 'iba', 'https://en.wikipedia.org/wiki/Boulevardier_(cocktail)');
INSERT INTO co.t_cocktails VALUES (101, 'Casino', 'https://en.wikipedia.org/wiki/Casino_(cocktail)');
INSERT INTO co.t_cocktails VALUES (102, 'Dry Martini', 'https://en.wikipedia.org/wiki/Martini_(cocktail)');
INSERT INTO co.t_cocktails VALUES (103, 'Fizz', 'https://en.wikipedia.org/wiki/Fizz_(cocktail)#Gin_fizz');
INSERT INTO co.t_cocktails VALUES (104, 'John Collins', 'https://en.wikipedia.org/wiki/John_Collins_(cocktail)');
INSERT INTO co.t_cocktails VALUES (105, 'The Last Word', 'https://en.wikipedia.org/wiki/Last_Word_(cocktail)');
INSERT INTO co.t_cocktails VALUES (106, 'Manhattan', 'https://en.wikipedia.org/wiki/Manhattan_(cocktail)');
INSERT INTO co.t_cocktails VALUES (107, 'Mary Pickford', 'https://en.wikipedia.org/wiki/Mary_Pickford_(cocktail)');
INSERT INTO co.t_cocktails VALUES (108, 'Old Fashioned', 'https://en.wikipedia.org/wiki/Old_fashioned_(cocktail)');
INSERT INTO co.t_cocktails VALUES (109, 'Paradise', 'https://en.wikipedia.org/wiki/Paradise_(cocktail)');
INSERT INTO co.t_cocktails VALUES (110, 'Fizz', 'https://en.wikipedia.org/wiki/Fizz_(cocktail)#Ramos_gin_fizz');
INSERT INTO co.t_cocktails VALUES (111, 'Rusty Nail', 'https://en.wikipedia.org/wiki/Rusty_Nail_(cocktail)');
INSERT INTO co.t_cocktails VALUES (112, 'Sidecar', 'https://en.wikipedia.org/wiki/Sidecar_(cocktail)');
INSERT INTO co.t_cocktails VALUES (113, 'Stinger', 'https://en.wikipedia.org/wiki/Stinger_(cocktail)');
INSERT INTO co.t_cocktails VALUES (114, 'Tuxedo', 'https://en.wikipedia.org/wiki/Tuxedo_(cocktail)');
INSERT INTO co.t_cocktails VALUES (115, 'Sours', 'https://en.wikipedia.org/wiki/Sour_(cocktail)#White_Lady');
INSERT INTO co.t_cocktails VALUES (116, 'Bellini', 'https://en.wikipedia.org/wiki/Bellini_(cocktail)');
INSERT INTO co.t_cocktails VALUES (117, 'Bloody Mary', 'https://en.wikipedia.org/wiki/Bloody_Mary_(cocktail)');
INSERT INTO co.t_cocktails VALUES (118, 'Cosmopolitan', 'https://en.wikipedia.org/wiki/Cosmopolitan_(cocktail)');
INSERT INTO co.t_cocktails VALUES (119, 'French 75', 'https://en.wikipedia.org/wiki/French_75_(cocktail)');
INSERT INTO co.t_cocktails VALUES (120, 'French Connection', 'https://en.wikipedia.org/wiki/French_Connection_(cocktail)');
INSERT INTO co.t_cocktails VALUES (121, 'Golden Dream', 'https://en.wikipedia.org/wiki/Golden_dream_(cocktail)');
INSERT INTO co.t_cocktails VALUES (122, 'Grasshopper', 'https://en.wikipedia.org/wiki/Grasshopper_(cocktail)');
INSERT INTO co.t_cocktails VALUES (123, 'Kir', 'https://en.wikipedia.org/wiki/Kir_(cocktail)');
INSERT INTO co.t_cocktails VALUES (124, 'Mimosa', 'https://en.wikipedia.org/wiki/Mimosa_(cocktail)');
INSERT INTO co.t_cocktails VALUES (125, 'Sea Breeze', 'https://en.wikipedia.org/wiki/Sea_Breeze_(cocktail)');
INSERT INTO co.t_cocktails VALUES (126, 'Tequila Sunrise', 'https://en.wikipedia.org/wiki/Tequila_Sunrise_(cocktail)');
INSERT INTO co.t_cocktails VALUES (127, 'Vesper', 'https://en.wikipedia.org/wiki/Vesper_(cocktail)');
INSERT INTO co.t_cocktails VALUES (128, 'Zombie', 'https://en.wikipedia.org/wiki/Zombie_(cocktail)');
INSERT INTO co.t_cocktails VALUES (129, 'Barracuda', 'https://en.wikipedia.org/wiki/Barracuda_(cocktail)');
INSERT INTO co.t_cocktails VALUES (130, 'Bee''s Knees', 'https://en.wikipedia.org/wiki/Bee%27s_Knees_(cocktail)');
INSERT INTO co.t_cocktails VALUES (131, 'Bramble', 'https://en.wikipedia.org/wiki/Bramble_(cocktail)');
INSERT INTO co.t_cocktails VALUES (132, 'Paloma', 'https://en.wikipedia.org/wiki/Paloma_(cocktail)');
INSERT INTO co.t_cocktails VALUES (133, 'South Side or Southside', 'https://en.wikipedia.org/wiki/South_Side_(cocktail)');
INSERT INTO co.t_cocktails VALUES (134, 'Yellow Bird', 'https://en.wikipedia.org/wiki/Yellow_Bird_(cocktail)');


SELECT pg_catalog.setval('co.t_cocktails_cocktail_id_seq', 134, true);


INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (60, 74);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 76);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 76);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (61, 77);
INSERT INTO co.t_cocktails_x_ingredients VALUES (62, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (62, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (62, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (62, 80);
INSERT INTO co.t_cocktails_x_ingredients VALUES (62, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (63, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (63, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (63, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 84);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (64, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 87);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (65, 76);
INSERT INTO co.t_cocktails_x_ingredients VALUES (66, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (66, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (66, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (66, 88);
INSERT INTO co.t_cocktails_x_ingredients VALUES (67, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (67, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (67, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (68, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (68, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (68, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (69, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (69, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (69, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (69, 89);
INSERT INTO co.t_cocktails_x_ingredients VALUES (69, 90);
INSERT INTO co.t_cocktails_x_ingredients VALUES (70, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (70, 91);
INSERT INTO co.t_cocktails_x_ingredients VALUES (70, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (70, 92);
INSERT INTO co.t_cocktails_x_ingredients VALUES (71, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (71, 93);
INSERT INTO co.t_cocktails_x_ingredients VALUES (71, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (72, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (72, 87);
INSERT INTO co.t_cocktails_x_ingredients VALUES (72, 92);
INSERT INTO co.t_cocktails_x_ingredients VALUES (72, 94);
INSERT INTO co.t_cocktails_x_ingredients VALUES (72, 95);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 96);
INSERT INTO co.t_cocktails_x_ingredients VALUES (73, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (74, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (74, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (74, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (75, 98);
INSERT INTO co.t_cocktails_x_ingredients VALUES (75, 98);
INSERT INTO co.t_cocktails_x_ingredients VALUES (75, 99);
INSERT INTO co.t_cocktails_x_ingredients VALUES (76, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (76, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (76, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (76, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (77, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (77, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (77, 100);
INSERT INTO co.t_cocktails_x_ingredients VALUES (78, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (78, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (78, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (78, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (78, 101);
INSERT INTO co.t_cocktails_x_ingredients VALUES (78, 88);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 102);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 96);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 103);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (79, 104);
INSERT INTO co.t_cocktails_x_ingredients VALUES (80, 105);
INSERT INTO co.t_cocktails_x_ingredients VALUES (80, 106);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 108);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 109);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 110);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 111);
INSERT INTO co.t_cocktails_x_ingredients VALUES (81, 112);
INSERT INTO co.t_cocktails_x_ingredients VALUES (82, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (82, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (82, 113);
INSERT INTO co.t_cocktails_x_ingredients VALUES (82, 114);
INSERT INTO co.t_cocktails_x_ingredients VALUES (82, 115);
INSERT INTO co.t_cocktails_x_ingredients VALUES (83, 116);
INSERT INTO co.t_cocktails_x_ingredients VALUES (83, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (83, 117);
INSERT INTO co.t_cocktails_x_ingredients VALUES (83, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (83, 116);
INSERT INTO co.t_cocktails_x_ingredients VALUES (84, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (84, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (84, 104);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 118);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 119);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (85, 74);
INSERT INTO co.t_cocktails_x_ingredients VALUES (86, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (86, 100);
INSERT INTO co.t_cocktails_x_ingredients VALUES (86, 100);
INSERT INTO co.t_cocktails_x_ingredients VALUES (86, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (86, 74);
INSERT INTO co.t_cocktails_x_ingredients VALUES (87, 120);
INSERT INTO co.t_cocktails_x_ingredients VALUES (87, 121);
INSERT INTO co.t_cocktails_x_ingredients VALUES (87, 122);
INSERT INTO co.t_cocktails_x_ingredients VALUES (88, 116);
INSERT INTO co.t_cocktails_x_ingredients VALUES (88, 116);
INSERT INTO co.t_cocktails_x_ingredients VALUES (88, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 115);
INSERT INTO co.t_cocktails_x_ingredients VALUES (89, 123);
INSERT INTO co.t_cocktails_x_ingredients VALUES (90, 124);
INSERT INTO co.t_cocktails_x_ingredients VALUES (90, 124);
INSERT INTO co.t_cocktails_x_ingredients VALUES (90, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (90, 125);
INSERT INTO co.t_cocktails_x_ingredients VALUES (91, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (91, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (91, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (91, 126);
INSERT INTO co.t_cocktails_x_ingredients VALUES (92, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (92, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (92, 119);
INSERT INTO co.t_cocktails_x_ingredients VALUES (92, 127);
INSERT INTO co.t_cocktails_x_ingredients VALUES (92, 114);
INSERT INTO co.t_cocktails_x_ingredients VALUES (92, 105);
INSERT INTO co.t_cocktails_x_ingredients VALUES (93, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (93, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (93, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (93, 117);
INSERT INTO co.t_cocktails_x_ingredients VALUES (94, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (94, 84);
INSERT INTO co.t_cocktails_x_ingredients VALUES (94, 119);
INSERT INTO co.t_cocktails_x_ingredients VALUES (94, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (94, 114);
INSERT INTO co.t_cocktails_x_ingredients VALUES (95, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (95, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (95, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (95, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (95, 74);
INSERT INTO co.t_cocktails_x_ingredients VALUES (96, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (96, 76);
INSERT INTO co.t_cocktails_x_ingredients VALUES (96, 76);
INSERT INTO co.t_cocktails_x_ingredients VALUES (96, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (96, 77);
INSERT INTO co.t_cocktails_x_ingredients VALUES (97, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (97, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (97, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (97, 80);
INSERT INTO co.t_cocktails_x_ingredients VALUES (97, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (98, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (98, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (98, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (99, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (99, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (99, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (99, 84);
INSERT INTO co.t_cocktails_x_ingredients VALUES (99, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (99, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (99, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (100, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (100, 87);
INSERT INTO co.t_cocktails_x_ingredients VALUES (100, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (100, 76);
INSERT INTO co.t_cocktails_x_ingredients VALUES (101, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (101, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (101, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (101, 88);
INSERT INTO co.t_cocktails_x_ingredients VALUES (102, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (102, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (102, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (103, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (103, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (103, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (104, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (104, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (104, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (104, 89);
INSERT INTO co.t_cocktails_x_ingredients VALUES (104, 90);
INSERT INTO co.t_cocktails_x_ingredients VALUES (105, 128);
INSERT INTO co.t_cocktails_x_ingredients VALUES (105, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (105, 129);
INSERT INTO co.t_cocktails_x_ingredients VALUES (105, 130);
INSERT INTO co.t_cocktails_x_ingredients VALUES (105, 131);
INSERT INTO co.t_cocktails_x_ingredients VALUES (106, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (106, 91);
INSERT INTO co.t_cocktails_x_ingredients VALUES (106, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (106, 92);
INSERT INTO co.t_cocktails_x_ingredients VALUES (107, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (107, 93);
INSERT INTO co.t_cocktails_x_ingredients VALUES (107, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (108, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (108, 87);
INSERT INTO co.t_cocktails_x_ingredients VALUES (108, 92);
INSERT INTO co.t_cocktails_x_ingredients VALUES (108, 94);
INSERT INTO co.t_cocktails_x_ingredients VALUES (108, 95);
INSERT INTO co.t_cocktails_x_ingredients VALUES (109, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (109, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (109, 96);
INSERT INTO co.t_cocktails_x_ingredients VALUES (109, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (110, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (110, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (110, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (111, 98);
INSERT INTO co.t_cocktails_x_ingredients VALUES (111, 98);
INSERT INTO co.t_cocktails_x_ingredients VALUES (111, 99);
INSERT INTO co.t_cocktails_x_ingredients VALUES (112, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (112, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (112, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (112, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (113, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (113, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (113, 100);
INSERT INTO co.t_cocktails_x_ingredients VALUES (114, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (114, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (114, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (114, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (114, 101);
INSERT INTO co.t_cocktails_x_ingredients VALUES (114, 88);
INSERT INTO co.t_cocktails_x_ingredients VALUES (115, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (115, 102);
INSERT INTO co.t_cocktails_x_ingredients VALUES (115, 96);
INSERT INTO co.t_cocktails_x_ingredients VALUES (115, 103);
INSERT INTO co.t_cocktails_x_ingredients VALUES (115, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (115, 104);
INSERT INTO co.t_cocktails_x_ingredients VALUES (116, 105);
INSERT INTO co.t_cocktails_x_ingredients VALUES (116, 106);
INSERT INTO co.t_cocktails_x_ingredients VALUES (117, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (117, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (117, 108);
INSERT INTO co.t_cocktails_x_ingredients VALUES (117, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (117, 109);
INSERT INTO co.t_cocktails_x_ingredients VALUES (117, 110);
INSERT INTO co.t_cocktails_x_ingredients VALUES (117, 111);
INSERT INTO co.t_cocktails_x_ingredients VALUES (117, 112);
INSERT INTO co.t_cocktails_x_ingredients VALUES (118, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (118, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (118, 113);
INSERT INTO co.t_cocktails_x_ingredients VALUES (118, 114);
INSERT INTO co.t_cocktails_x_ingredients VALUES (118, 115);
INSERT INTO co.t_cocktails_x_ingredients VALUES (119, 116);
INSERT INTO co.t_cocktails_x_ingredients VALUES (119, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (119, 117);
INSERT INTO co.t_cocktails_x_ingredients VALUES (119, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (119, 116);
INSERT INTO co.t_cocktails_x_ingredients VALUES (120, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (120, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (120, 104);
INSERT INTO co.t_cocktails_x_ingredients VALUES (121, 118);
INSERT INTO co.t_cocktails_x_ingredients VALUES (121, 119);
INSERT INTO co.t_cocktails_x_ingredients VALUES (121, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (121, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (121, 74);
INSERT INTO co.t_cocktails_x_ingredients VALUES (122, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (122, 100);
INSERT INTO co.t_cocktails_x_ingredients VALUES (122, 100);
INSERT INTO co.t_cocktails_x_ingredients VALUES (122, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (122, 74);
INSERT INTO co.t_cocktails_x_ingredients VALUES (123, 120);
INSERT INTO co.t_cocktails_x_ingredients VALUES (123, 121);
INSERT INTO co.t_cocktails_x_ingredients VALUES (123, 122);
INSERT INTO co.t_cocktails_x_ingredients VALUES (124, 116);
INSERT INTO co.t_cocktails_x_ingredients VALUES (124, 116);
INSERT INTO co.t_cocktails_x_ingredients VALUES (124, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (125, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (125, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (125, 115);
INSERT INTO co.t_cocktails_x_ingredients VALUES (125, 123);
INSERT INTO co.t_cocktails_x_ingredients VALUES (126, 124);
INSERT INTO co.t_cocktails_x_ingredients VALUES (126, 124);
INSERT INTO co.t_cocktails_x_ingredients VALUES (126, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (126, 125);
INSERT INTO co.t_cocktails_x_ingredients VALUES (127, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (127, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (127, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (127, 126);
INSERT INTO co.t_cocktails_x_ingredients VALUES (128, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (128, 132);
INSERT INTO co.t_cocktails_x_ingredients VALUES (128, 133);
INSERT INTO co.t_cocktails_x_ingredients VALUES (128, 129);
INSERT INTO co.t_cocktails_x_ingredients VALUES (129, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (129, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (129, 119);
INSERT INTO co.t_cocktails_x_ingredients VALUES (129, 127);
INSERT INTO co.t_cocktails_x_ingredients VALUES (129, 114);
INSERT INTO co.t_cocktails_x_ingredients VALUES (129, 105);
INSERT INTO co.t_cocktails_x_ingredients VALUES (130, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (131, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (131, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (131, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (131, 117);
INSERT INTO co.t_cocktails_x_ingredients VALUES (132, 124);
INSERT INTO co.t_cocktails_x_ingredients VALUES (132, 124);
INSERT INTO co.t_cocktails_x_ingredients VALUES (133, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (133, 134);
INSERT INTO co.t_cocktails_x_ingredients VALUES (134, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (134, 84);
INSERT INTO co.t_cocktails_x_ingredients VALUES (134, 119);
INSERT INTO co.t_cocktails_x_ingredients VALUES (134, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (134, 114);


SELECT pg_catalog.setval('co.t_cocktails_x_ingredients_cocktail_id_seq', 1, false);


INSERT INTO co.t_ingredients VALUES (72, 'cognac');
INSERT INTO co.t_ingredients VALUES (73, 'crème de cacao');
INSERT INTO co.t_ingredients VALUES (74, 'cream');
INSERT INTO co.t_ingredients VALUES (75, 'vermouth');
INSERT INTO co.t_ingredients VALUES (76, 'campari');
INSERT INTO co.t_ingredients VALUES (77, 'soda water');
INSERT INTO co.t_ingredients VALUES (78, 'gin');
INSERT INTO co.t_ingredients VALUES (79, 'calvados');
INSERT INTO co.t_ingredients VALUES (80, 'apricot brandy');
INSERT INTO co.t_ingredients VALUES (81, 'maraschino');
INSERT INTO co.t_ingredients VALUES (82, 'rum');
INSERT INTO co.t_ingredients VALUES (83, 'triple sec');
INSERT INTO co.t_ingredients VALUES (84, 'white rum');
INSERT INTO co.t_ingredients VALUES (85, 'lemon juice');
INSERT INTO co.t_ingredients VALUES (86, 'whiskey');
INSERT INTO co.t_ingredients VALUES (87, 'bourbon');
INSERT INTO co.t_ingredients VALUES (88, 'orange bitters');
INSERT INTO co.t_ingredients VALUES (89, 'sugar syrup');
INSERT INTO co.t_ingredients VALUES (90, 'carbonated water');
INSERT INTO co.t_ingredients VALUES (91, 'cl');
INSERT INTO co.t_ingredients VALUES (92, 'angostura bitters');
INSERT INTO co.t_ingredients VALUES (93, 'grenadine');
INSERT INTO co.t_ingredients VALUES (94, 'sugar');
INSERT INTO co.t_ingredients VALUES (95, 'water');
INSERT INTO co.t_ingredients VALUES (96, 'brandy');
INSERT INTO co.t_ingredients VALUES (97, 'orange juice');
INSERT INTO co.t_ingredients VALUES (98, 'scotch whisky');
INSERT INTO co.t_ingredients VALUES (99, 'drambuie');
INSERT INTO co.t_ingredients VALUES (100, 'crème de menthe');
INSERT INTO co.t_ingredients VALUES (101, 'absinthe');
INSERT INTO co.t_ingredients VALUES (102, 'bourbon whiskey');
INSERT INTO co.t_ingredients VALUES (103, 'pisco');
INSERT INTO co.t_ingredients VALUES (104, 'amaretto');
INSERT INTO co.t_ingredients VALUES (105, 'prosecco');
INSERT INTO co.t_ingredients VALUES (106, 'peach');
INSERT INTO co.t_ingredients VALUES (107, 'vodka');
INSERT INTO co.t_ingredients VALUES (108, 'tomato juice');
INSERT INTO co.t_ingredients VALUES (109, 'worcestershire sauce');
INSERT INTO co.t_ingredients VALUES (110, 'tabasco sauce');
INSERT INTO co.t_ingredients VALUES (111, 'celery salt');
INSERT INTO co.t_ingredients VALUES (112, 'black pepper');
INSERT INTO co.t_ingredients VALUES (113, 'cointreau');
INSERT INTO co.t_ingredients VALUES (114, 'lime juice');
INSERT INTO co.t_ingredients VALUES (115, 'cranberry juice');
INSERT INTO co.t_ingredients VALUES (116, 'champagne');
INSERT INTO co.t_ingredients VALUES (117, 'simple syrup');
INSERT INTO co.t_ingredients VALUES (118, 'orange-flavored liqueur');
INSERT INTO co.t_ingredients VALUES (119, 'galliano');
INSERT INTO co.t_ingredients VALUES (120, 'wine');
INSERT INTO co.t_ingredients VALUES (121, 'white wine');
INSERT INTO co.t_ingredients VALUES (122, 'crème de cassis');
INSERT INTO co.t_ingredients VALUES (123, 'grapefruit juice');
INSERT INTO co.t_ingredients VALUES (124, 'tequila');
INSERT INTO co.t_ingredients VALUES (125, 'grenadine syrup');
INSERT INTO co.t_ingredients VALUES (126, 'lillet blanc');
INSERT INTO co.t_ingredients VALUES (127, 'pineapple juice');
INSERT INTO co.t_ingredients VALUES (128, 'green chartreuse');
INSERT INTO co.t_ingredients VALUES (129, 'lime');
INSERT INTO co.t_ingredients VALUES (130, 'chartreuse');
INSERT INTO co.t_ingredients VALUES (131, 'maraschino liqueur');
INSERT INTO co.t_ingredients VALUES (132, 'golden rum');
INSERT INTO co.t_ingredients VALUES (133, 'falernum');
INSERT INTO co.t_ingredients VALUES (134, '[1]');


SELECT pg_catalog.setval('co.t_ingredients_ingrediend_id_seq', 134, true);


